/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.JOptionPane;

/**
 *
 * @author luizo
 */
public class TelacarregamentoImobi extends javax.swing.JFrame {

    /**
     * Creates new form TelacarregamentoImobi
     */
    public TelacarregamentoImobi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        porcentagem = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentagem.setBackground(new java.awt.Color(0, 0, 0));
        porcentagem.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(porcentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 60, 30));

        progresso.setBackground(new java.awt.Color(255, 255, 255));
        progresso.setForeground(new java.awt.Color(0, 0, 0));
        progresso.setOpaque(true);
        jPanel1.add(progresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 360, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/origami-removebg-preview1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 140, 210, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/origami__1_-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, -30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        TelacarregamentoImobi load = new TelacarregamentoImobi();
        load.setVisible(true);
        
        try{
            for (int i = 0; i <=100; i+=3)
                
            {
                Thread.sleep(70);
                load.progresso.setValue(i);
                load.porcentagem.setText(Integer.toString(i) + "%");
            } load.dispose();
                    
            
    
          TelaLogin login = new TelaLogin();
          login.setVisible(true);
            }catch(InterruptedException e) {
    JOptionPane.showConfirmDialog(null,"erro");
        
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel porcentagem;
    private javax.swing.JProgressBar progresso;
    // End of variables declaration//GEN-END:variables
}
